ALTER TABLE AppliedConcentratedLoads ADD CHECK (Direction >= 1 AND Direction <= 6);
ALTER TABLE AppliedDisplacements ADD CHECK (Direction >= 1 AND Direction <= 6);
ALTER TABLE BeamGroups ADD CHECK (Displacement = 'small' OR Displacement = 'large' OR 'default');
ALTER TABLE BeamGroups ADD CHECK (Result = 'forces' OR Result = 'stresses');
ALTER TABLE BeamGroups ADD CHECK (Inistrain = 'none' OR Inistrain = 'nodal' OR Inistrain = 'element' OR Inistrain = 'both');
ALTER TABLE BeamGroups ADD CHECK (REtype = 'none' OR REtype = 'absolute' OR REtype = 'infinite');
ALTER TABLE BeamGroups ADD CHECK (MC = 'yes' OR MC = 'no');
ALTER TABLE BeamLoads ADD CHECK (Face = 1 OR Face = 2);
ALTER TABLE BeamLoads ADD CHECK (DirectFilter >= 0 AND DirectFilter <=3);
ALTER TABLE Beams ADD CHECK (Save = 'default' OR Save = 'yes' OR Save = 'no');
ALTER TABLE ContactGroup3 ADD CHECK (Forces = 'yes' OR Forces = 'no');
ALTER TABLE ContactGroup3 ADD CHECK (Tractions = 'yes' OR Tractions = 'no');
ALTER TABLE ContactGroup3 ADD CHECK (IniPenetration = 'allowed' OR IniPenetration = 'print' OR IniPenetration = 'discarded');
ALTER TABLE ContactGroup3 ADD CHECK (PenetrAlgorithm = 'one' OR PenetrAlgorithm = 'two');
ALTER TABLE ContactGroup3 ADD CHECK ( (Off_Set = 0.0 AND PenetrAlgorithm = 'one) OR (Off_Set = 0.001 AND PenetrAlgorithm = 'two') );
ALTER TABLE ContactGroup3 ADD CHECK (Tied = 'no' OR Tied = 'small');
ALTER TABLE ContactPairs ADD CHECK (FContactor >= 0 AND FContactor <= 1);
ALTER TABLE ContactPairs ADD CHECK (FTarget >= 0 AND FTarget <= 1);
ALTER TABLE ElasticMaterials ADD CHECK (e > 0.0);
ALTER TABLE ElasticMaterials ADD CHECK (NU > -1 AND NU < 0.5);
ALTER TABLE ElasticMaterials ADD CHECK (ALPHA >= 0.0);
ALTER TABLE Endreleases ADD CHECK (Moment1 >= 1 AND Moment1 <= 12);
ALTER TABLE Endreleases ADD CHECK (Moment2 >= 1 AND Moment2 <= 12);
ALTER TABLE Endreleases ADD CHECK (Moment3 >= 1 AND Moment3 <= 12);
ALTER TABLE Endreleases ADD CHECK (Moment4 >= 1 AND Moment4 <= 12);
ALTER TABLE Endreleases ADD CHECK (Moment5 >= 1 AND Moment5 <= 12);
ALTER TABLE Endreleases ADD CHECK (Moment6 >= 1 AND Moment6 <= 12);
ALTER TABLE GeneralGroups ADD CHECK (Result = 'stresses' OR Result = 'forces');
ALTER TABLE GeneralGroups ADD CHECK (SkewSystem = 'yes' OR SkewSystem = 'no');
ALTER TABLE Generals ADD CHECK (Save = 'default' OR Save = 'yes' OR Save = 'no');
ALTER TABLE IsobeamGroups ADD CHECK (Displacement = 'small' OR Displacement = 'large' OR Displacement = 'default');
ALTER TABLE IsobeamGroups ADD CHECK (Result = 'forces' OR Result = 'stresses');
ALTER TABLE IsobeamGroups ADD CHECK (IniStrain = 'none' OR IniStrain = 'nodal' OR IniStrain = 'element' OR IniStrain = 'both');
ALTER TABLE Isobeams ADD CHECK (Save = 'default' OR Save = 'yes' OR Save = 'no');
ALTER TABLE Links ADD CHECK (Displacement = 'default' OR Displacement = 'small' OR Displacement = 'large');
ALTER TABLE Matrices ADD CHECK (MatrixType = 'stiffness' OR MatrixType = 'mass' OR MatrixType = 'damping' OR MatrixType = 'stress');
ALTER TABLE Matrices ADD CHECK ( (MatrixType != 'stress' AND NS = 0) OR MatrixType = 'stress');
ALTER TABLE MCrigidities ADD CHECK (Beta > 0.0 AND Beta < 1.0);
ALTER TABLE MCrigidities ADD CHECK (ForceAxID >= 1);
ALTER TABLE MCrigidities ADD CHECK (AxialCF >= 1);
ALTER TABLE MCrigidities ADD CHECK (BendingCF >= 1);
ALTER TABLE MCrigidities ADD CHECK (TorsionCF >= 1);
ALTER TABLE NTNContact ADD CHECK (PrintRes = 'yes' OR PrintRes = 'no' OR PrintRes = 'default');
ALTER TABLE NTNContact ADD CHECK (SaveRes = 'yes' OR SaveRes = 'no' OR SaveRes = 'default');
ALTER TABLE PlasticBIMaterials ADD CHECK (Hardening = 'isotropic' OR Hardening = 'kinematic');
ALTER TABLE PlasticBIMaterials ADD CHECK (E > 0.0);
ALTER TABLE PlasticBIMaterials ADD CHECK (NU > -1 AND NU < 0.5);
ALTER TABLE PlasticBIMaterials ADD CHECK (ALPHA >= 0.0);
ALTER TABLE PlasticMIMaterials ADD CHECK (Hardening = 'isotropic' OR Hardening = 'kinematic');
ALTER TABLE PlasticMIMaterials ADD CHECK (E > 0.0);
ALTER TABLE PlasticMIMaterials ADD CHECK (NU > -1 AND Nu < 0.5);
ALTER TABLE PlasticMIMaterials ADD CHECK (ALPHA >= 0.0);
ALTER TABLE PlateGroups ADD CHECK (Displacement = 'small' OR Displacement = 'large' OR Displacement = 'default');
ALTER TABLE PlateGroups ADD CHECK (Result = 'forces' OR result = 'stress-resultants');
ALTER TABLE PlateGroups ADD CHECK (IniStrain = 'none' OR IniStrain = 'nodal' OR IniStrain = 'element' OR IniStrain = 'both');
ALTER TABLE Plates ADD CHECK (Save = 'default' OR Save ='yes' OR Save = 'no');
ALTER TABLE Properties ADD CHECK (Rupture = 'yes' OR Rupture = 'no');
ALTER TABLE PropertySets ADD CHECK (Nonlinear = 'yes' OR Nonlinear = 'no');
ALTER TABLE SectionRect ADD CHECK (IShear = 'yes' OR IShear = 'no');
ALTER TABLE ShellDOFs ADD CHECK (DOFnumber = 'five' OR DOFnumber = 'six' OR DOFnumber = 'automatic');
ALTER TABLE ShellGroups ADD CHECK (Displacement = 'small' OR Displacement = 'large' OR Displacement = 'default');
ALTER TABLE ShellGroups ADD CHECK (Result = 'forces' OR Result = 'stresses');
ALTER TABLE ShellGroups ADD CHECK (StressReference = 'global' OR StressReference = 'local' OR StressReference = 'matertial');
ALTER TABLE ShellGroups ADD CHECK (SectionResult >= -2 AND SectionResult <= 2);
ALTER TABLE ShellLayers ADD CHECK (PThick <= 100);
ALTER TABLE ShellPressure ADD CHECK (Face >= 1 AND Face <= 4);
ALTER TABLE ShellPressure ADD CHECK (DirectFilter >= 0 AND DirectFilter <= 3);
ALTER TABLE Shells ADD CHECK (NodeAmount = 4 OR NodeAmount = 8 OR NodeAmount = 9);
ALTER TABLE Shells ADD CHECK (Save = 'yes' OR Save  = 'no' OR Save = 'default');
ALTER TABLE SpringGroups ADD CHECK (Results = 'forces' OR Results = 'stresses');
ALTER TABLE SpringGroups ADD CHECK (Nonlinear = 'yes' OR Nonlinear = 'no');
ALTER TABLE SpringGroups ADD CHECK (SkewSystem = 'yes' OR SkewSystem = 'no');
ALTER TABLE SpringGroups ADD CHECK (Bolt = 'none' OR Bolt = 'tied');
ALTER TABLE Springs ADD CHECK (Save = 'default' OR Save = 'yes' OR Save = 'no');
ALTER TABLE Systems ADD CHECK (Type = 'cartesiam' OR Type = 'cylindrical' OR Type = 'spherical');
ALTER TABLE Systems ADD CHECK (Mode = 1 OR Mode = 3);
ALTER TABLE ThreedsolidGroups ADD CHECK (Displacement = 'small' OR Displacement = 'large' OR Displacement = 'default');
ALTER TABLE ThreedsolidGroups ADD CHECK (Result = 'forces' OR Result = 'stresses');
ALTER TABLE Threedsolid ADD CHECK (Save = 'yes' OR save = 'no' OR save = 'default');
ALTER TABLE Trusses ADD CHECK (Save = 'yes' OR Save = 'no' OR Save = 'default');
ALTER TABLE TrussGroups ADD CHECK (Displacement = 'small' OR Displacement = 'large' OR Displacement = 'default');
ALTER TABLE TrussGroups ADD CHECK (GAPS = 'yes' OR GAPS = 'no');
ALTER TABLE TrussGroups ADD CHECK (IniStrain = 'none' OR IniStrain = 'nodal' OR IniStrain = 'element' OR IniStrain = 'both');
ALTER TABLE TwodsolidGroups ADD CHECK (Subtype = 'axisymmetric' OR Subtype = 'strain' OR Subtype = 'stress2' OR Subtype = 'stress3' OR Subtype = 'strain3');
ALTER TABLE TwodsolidGroups ADD CHECK (Displacement = 'small' OR Displacement = 'large' OR Displacement = 'default');
ALTER TABLE TwodsolidGroups ADD CHECK (Result = 'forces' OR Result = 'stresses');
ALTER TABLE Twodsolids ADD CHECK (NodeAmount = 4 OR NodeAmount = 8 OR NodeAmount = 9);
ALTER TABLE Twodsolids ADD CHECK (Save = 'yes' OR Save = 'no' OR Save = 'default');
